# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common
	  pod 'WeexSDK'
    pod 'WeexPluginLoader'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
end

target 'DMWeexSingle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMWeexSingle
  common
end